
```{r}
#all the setup stuff
library(tidytuesdayR)
library(tidyverse)
tuesdata <- tt_load('2020-02-18')
fc <- tuesdata$food_consumption

#| fig-alt: "a histogram of food consuption with combined countries, faceted by food type. aside from dairy products which are the most evenly spread, other categories like eggs, lamb, and soybeans are less common. source: https://github.com/rfordatascience/tidytuesday/blob/main/data/2020/2020-02-18/readme.md"

#honest to god, i really did not know how to make an effective graph with this many countries. this one is clearly coherent in telling you the consumption of different food types overall, but how the hell would you be able to tell if i filled by country? it has the effective vis properties, it's just not great. i am aware. 
fc |>
  ggplot(aes(x = consumption)) +
  geom_histogram() +
  facet_wrap(~food_category) +
  labs(x = "Consumption", y = "Food Category")

```
```{r}
#| fig-width: 22
#| fig-alt: "A dotplot of food consumption per country, seperated by food type. The most variation in consumption is with wheat products, dairy products, and rice. source: https://github.com/rfordatascience/tidytuesday/blob/main/data/2020/2020-02-18/readme.md"

#but at least I tried to color it? to be fair, this one does show the variance of each food category a lot better, but a dotplot was the only way i was able to get a not super hideous result. 
fc |>
  ggplot(aes(x = consumption, y = food_category, color = country)) +
geom_point() +
  scale_colour_viridis_d() +
  labs(x = "Consumption", y = "Food Category")
```

